### ISSUE TITLE
[Action] Add mermaid.js support to the website

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#101]
ref PR https://github.com/cncf/tag-env-sustainability/pull/100
 
We are using [mermaid.js](https://mermaid.js.org/) to create diagrams. [mermaid.js is supported by github](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) in markdown files. Is it possible to enable it for our website?
Quick search found this: https://discourse.gohugo.io/t/use-mermaid-with-code-fences/17211

right now the mermaid code block does not render (see screenshot)
![Screenshot by Dropbox Capture](https://github.com/cncf/tag-env-sustainability/assets/58054077/5c8438dc-1d6b-4558-8989-5d884940aa8b)

**Comment by holistic-developer** [comment]
I tried fixing this yesterday during the meeting and had a look again today.
Since we are using the **docsy** theme this is a built in feature an "just" needs to be enabled in the **config.toml**
```
[params.mermaid]
enable = true
```
A local test worked, but it is not happy with some of the syntax we are using within the mermaid charts:
![image](https://github.com/cncf/tag-env-sustainability/assets/57600104/d6f32b55-b258-4d9d-9339-d9c9a9e6141e)
It is not able to handle the titles in the charts. E.g.:
```
---
title: The Observability Domain of the Sustainable Cloud Computing Landscape
---
```
If I remove those it works fine.
On https://mermaid.live the diagrams look just fine (even with the titles), but do they add much value? Are they in there for accessibility reasons?

**Comment by leonardpahlke** [comment]
@holistic-developer awesome! Sure, we can remove the titles. Would you like to open a PR to add support? Thanks!

**Comment by leonardpahlke** [comment]
Thanks @holistic-developer !
