### ISSUE TITLE
[Action] Add pdf file browsing support to the website

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#102]
TAG ENV has created some presentations in the past that are worth showing on the [website](https://tag-env-sustainability.cncf.io/) (2022 survey results, 2023 KCCN TAG ENV talk, Getting started with TAG ENV talk).

I found the extension https://github.com/anvithks/hugo-embed-pdf-shortcode that we can use. I'm sure there are other options as well. @cjyabraham what are your thoughts on this?

**Comment by cjyabraham** [comment]
I don't like it that much. My preference as a user would be to just pop the PDF open in a new tab (or download it) rather than have a small window in the current page that I view it in. For example, see [their demo here](https://hugo-embed-pdf.netlify.app/demo/). Isn't it nicer to just view [the PDF in its own browser tab](https://hugo-embed-pdf.netlify.app/demo/hugo-embed-pdf-sample.pdf)?

**Comment by leonardpahlke** [comment]
Right, yes, viewing the pdf regularly in the browser, downloading it etc is best. My thought was that a link can go unnoticed quickly and a preview would highlight the PDF better. But we can highlight it with other Markdown blocks 👍

**Comment by cjyabraham** [comment]
Sure. Or grab an image of the cover of the PDF and use that on the page as a link to the full PDF. We do something similar [when we list PDFs on the CNCF site](https://www.cncf.io/reports/edge-native-applications-principles-whitepaper/).

**Comment by leonardpahlke** [comment]
That's a great example. I can see we adopt this style too, thanks! :)
