### ISSUE TITLE
[Tracking, Cloud Native Sustainability Week] Support Local Meetup Organizers

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#134]
Part of https://github.com/cncf/tag-env-sustainability/issues/95

There are a lot of meetups organized during this event and likely questions will arise. It would help if a few folks had their eye on any questions that may come up and help facilitate those and, in the process, improve the program.

This [document](https://docs.google.com/document/d/1s28lqqc3IBAMw4T7n13zfyAuUEEc3I4_xhPxCLA4_dk/edit) describes the program and tries to answer questions preemptively. Possibly, a FAQ section could be helpful.

**Comment by Bamistand** [comment]
Happy to help

**Comment by shane-wang** [comment]
Hi all.

I'm Shane Wang, an Intel employee working on cloud native and one of the CNCF ambassadors located at Shanghai, China. After being reached out by Sam Yuan from IBM and Jiaju Zhang from Red Hat and discussing together, we agreed to make the following changes for the local meetups in China for Cloud Native Sustainability Week, could someone and @leonardpahlke please help check whether it works for the entire event?

* In order to increase the influence, we would like to host the meetup at Beijing and Shanghai simultaneously with live-broadcasting. 
* As an ambassador, I will initiate the local meetup in China (Beijing and Shanghai) so the meetup can be part of CNCF official meetups and use CNCF logos.
* Regarding many local events' conflicts in Oct., we want to postpone the meetup to be the weekend of Nov. 4 or 5, but we also want to participate into the umbrella of "Cloud Native Sustainability Week", is it OK?

Thanks.

**Comment by leonardpahlke** [comment]
Hey @shane-wang :)

> In order to increase the influence, we would like to host the physical meetup at Beijing Red Hat office and Shanghai Intel office simultaneously with live-broadcasting.

Thats a great idea. I know the folks in India are also planning to sync up their meetups. 

> Regarding many local events' conflicts in Oct., we want to postpone the meetup to be the weekend of Nov. 4 or 5, but we also want to participate into the umbrella of "Cloud Native Sustainability Week", is it OK?

The cloud native sustainability week will be scheduled for the second week of October. This week is overall the best fit, it is not possible to a week which fits everyone. It would be wonderful if you could arrange to schedule the meetup during the second week of October, so we can build up as a community as much momentum as possible! You can also host a meetup about cloud native sustainability at any other time, but we may not be able to sync up all the efforts we planned for the cloud native sustainability week.

**Comment by pichuang** [comment]
Is there a standardised name for the conference? Or is it up to the local organisers to decide?

**Comment by leonardpahlke** [comment]
Good question. Yes, I think we should do that. Have a common scheme like `CNCF Sustainability Week - Taiwan` to the meetups can be easily identified. We can put that on the guide. I will schedule today two meetings for next week to discuss the event so all local meetup organizers know about the current state, the plan etc.

**Comment by pichuang** [comment]
@leonardpahlke 
We recently received an invitaion from the [Green Software Foundation (GSF)](https://greensoftware.foundation/) to organise an in-person event in Taiwan in conjunction with Cloud Native Sustainability Week (CMSW), but the GSF speaker is only available on the week of 10/24 (Week 43).

Since Taiwan is at very early stage of Sustainability issues, I'd like to consider postponing the event to the week of 10/24 (Week 43) instead of Week 41 to accommodate the availability of the GSF speaker.

May I ask if this is possible?

**Comment by guidemetothemoon** [comment]
**Note to local meetup organizers:** we have created a CFP form where we added a drop-down list where a speaker can choose whether they would like to present at a virtual meetup or any of the confirmed local meetups. Entries for the local meetups will be shared with the respective organizers, and this is meant as an additional way to submit speaker interest for a local meetup. As a local meetup organizer you can still use a dedicated CFP page if you'd like. CFP form is available here: https://docs.google.com/forms/d/1bCJQ6yqM5NnGDR_pK-jKgrD8qoR5ehkhjwVks_XLHHs/edit
The plan is to publish the CFP form next week - if you have any input or comments, please share those in the related GitHub issue #131 or in the Slack channel 😊

**Comment by guidemetothemoon** [comment]
CFP for Cloud Native Sustainability Week virtual meetup and local meetups is now open!🥳

This link can be shared with others: https://docs.google.com/forms/d/e/1FAIpQLSdwy7gaIbgyfITJhDC1axzR9AuO6rPuZGyi2nZQynILgP77qQ/viewform?usp=sf_link

As mentioned earlier submissions to local meetups will be shared with respective local meetup oranizers and will be aggregated in this document: https://docs.google.com/spreadsheets/d/1i7UcKr9Fz1QYqCawrjBwWDpTsUZ1HQRFNWSVRAvQcCE/edit?usp=sharing

We have published announcement both on our LinkedIn page (give it a follow😊) and Twitter/X - please spread the love!
LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:7100112838999875584
Twitter/X: https://twitter.com/CNCFEnvTAG/status/1694348695045603790?s=20

Thank you!😊

**Comment by AntonioDiTuri** [comment]
I created  a to-do list for the local event organizers: I hope it can be helpful to everybody

https://github.com/cncf/tag-env-sustainability/issues/224

Feel free to provide inputs :)
