### ISSUE TITLE
APAC meeting  Discussion issue - 25th June 2024

### ISSUE THREAD

**Issue by saiyam1814** [cncf/tag-env-sustainability#441]
### Description

This is for the Agenda prepration for 25th June meeting for tag sustainability APAC timezone. 

### Outcome

This will give concrete meeting discussion points 

### To-Do

- [ ] ...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamYuan1990** [comment]
we make integration between Equinix and kepler-action,  Equinix provides BM env, and kepler-action for set up k8s cluster (from set up k8s or config an existing k8s cluster), some open discuss at  https://github.com/sustainable-computing-io/kepler-metal-ci/issues/45 
considering as we use this approach to verify kepler, and, obviously we can use this approach or pattern to verify other project.

**Comment by SamYuan1990** [comment]
<img width="877" alt="image" src="https://github.com/cncf/tag-env-sustainability/assets/7820992/b74bcbcf-929e-4791-a450-c30deb4a43e3">

@rootfs , @leonardpahlke  in 25th meeting, if I am available, I hope to discuss a general CI/CD pipeline with high level design above.
which has three levels:
- 1st a k8s, which running with any kind of k8s cluster provider.
- 2nd take kepler-action as example, a github action to prepare and config any existing k8s cluster with necessary CNCF components which use for 3rd part.
- 3rd part a Tekton based pipeline for project.

in the 3rd pipeline, 
which running stress testing for target project(for example maybe stress ng for kepler, jmeter for nginx)
collecting metric data
validation or calculate metrics such as SCI (Software Carbon Intensity)

so that, for different version release of software, the SCI can be compared, and used for audit for project.
optionally at the 1st level, infrastructure also supports build up a k8s from a new BM instance.

**Comment by saiyam1814** [comment]
Completed !
