### ISSUE TITLE
[Tracking] Conferences

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf/tag-env-sustainability#59]
#### Description

This is to track conferences that focus on environmental sustainability, have green tracks, or may be relevant in terms of speaking opportunities/outreach for the Environmental Sustainability TAG.

This list may also inform the work of future Working Group that may be focused on comms & outreach.

#### Upcoming Conferences
- KubeCon
  -  Issue that tracks KubeCon EU '23 TAG talk: https://github.com/cncf/tag-env-sustainability/issues/49
- FOSDEM
  - Issue that tracks FOSDEM2023: ttps://github.com/cncf/tag-env-sustainability/issues/56
- LF Foundation SustainabilityCon
  - SustainabilityCon NA 23: **CFPs open until 4th February 2023** https://events.linuxfoundation.org/open-source-summit-north-america/about/sustainabilitycon/
  - SustainabilityCon EU 23: https://events.linuxfoundation.org/open-source-summit-europe/

#### Past Conferences
- [Green Software Summit](https://summit.greensoftware.foundation/)
- [Google Sustainability Summit](https://cloudonair.withgoogle.com/events/summit-sustainability-2022)
 
Feel free to edit this list or add a comment below with more conferences to be tracked!

**Comment by guidemetothemoon** [comment]
Yes, +1 to having it as part of the website! A workflow could totally be helpful to make the process of continuously updating the list more automated and smooth. I can help out with it, if needed.

**Comment by catblade** [comment]
+1 re website additions.

**Comment by leonardpahlke** [comment]
+1 re website additions.

**Comment by immavalls** [comment]
Let me know if I can help

**Comment by guidemetothemoon** [comment]
So, I thought more about this topic lately and thought I could share some thoughts and see what others think. 

I was looking into potential ways to track sustainability-related sessions in conferences and tech events programmatically, but that's not quite that easy at this point unfortunately. There's no single, public place where this information is collected, and I couldn't find any useful tools we could use to search for and filter this type of information so I'm not sure if there's a good way currently to collect this information automatically without developing something ourselves...I also saw someone asking on Slack if all the conferences and events have a session on sustainability, and I don't think that's the case. At least yet. KubeCon+CloudNativeCon and Open Source Summit is one thing, but once we consider other conferences and maybe even meetups (local/global) I think we would still need to do some checking and verification prior to mentioning it on our website. But if you disagree, please comment here as well.

If we were to follow the path of less resistance that is relatively lightweight to introduce, I would consider having a lightweight way to submit past and upcoming sessions and conferences related to sustainability that would also be easy to use for non-technical people who don't have much knowledge about GitHub and pull request process. We can then add these submissions to be displayed in our Events section of the website: https://tag-env-sustainability.cncf.io/events 

Regarding this I have a few thoughts:
- GSF has for example a separate item in GitHub Discussions, where people can submit information about past/upcoming talks related to green software: https://github.com/orgs/Green-Software-Foundation/discussions/22 . We're not using GH Discussions currently, but we could just have a tracking issue like this one, where people could add suggestions in the comments and we could put those suggestions up on a website. Or for less technical people we could also have a submission form of some kind (like Google Form), that we could also link at the top of the Events section of the website. We could also link the tracking issue on the website if we were to go exclusively for that option.
Not everyone would be comfortable or willing to learn themselves the website structure and the PR process in order to be able to submit an event so I think it's important that we have a simpler way to submit this information.
Another option is to implement a submission form directly on the website (in the same way like there are contact forms), but it may be a bigger change.

- We may need to look into how Events section is structured currently. In some cases we want to have a longer post to provide extensive information regarding all the sustainability-related sessions/tracks at a larger conference, but in some cases we would want to have some kind of a table that could provide a general overview and list conferences as well as individual sessions that may happen at local or global meetups, be it virtual or in-person, so that people can get a nice overview without needing to click into every single post.

So a few enhancements I would propose for the Events section are:
  * Have a visible link at the top of the Events page to some kind of form/item where people can submit past/upcoming sessions and events on the topic;
  * When someone goes directly to the Events section we could probably have an index.md file that contains a table of all conferences and sessions on the topic. If there are events that have a dedicated post that goes more into detail, we could link it directly in the table, as part of the respective entry. Like, for example, have an entry for "Open Source Summit NA 2023" in the table that links to https://tag-env-sustainability.cncf.io/events/2023-oss-na, which is a dedicated post going into more details.
  * We were also talking about some possibilities for automation with GitHub Actions. I'm not sure if there's much we can do if we were to go through a PR process, where you need to create a new Markdown file, add content to it, etc. But if we were to have some kind of a table, we could potentially automate populating that table with new entries based on the new submissions from somewhere that follow a specific format. I'm just thinking loudly here, but there may be some possibilities at least that we could look into long-term.
  
Thoughts?😊

**Comment by leonardpahlke** [comment]
:+1: yes, we can definitely enhance the events page. Currently, we publish smth under the events tab if we as a TAG organize in person meetups at the conference, I like that - we should keep this. But we can add another page to discover any sustainability related talks. I think thats a great idea. If we go down this path, I would like to see that we establish a low maintenance process, since this can go out of hand quickly. Recently, Al-Hussein (do not know his GH username) posted in Slack tag-env-sustainability a list of sustainability related talks which he scraped off from sched. He already has a script to generate this list. That would be a programmatic approach to generate this list, which IMO is in the scope of the TAG. We may want to use this. I like the ideas you proposed. @guidemetothemoon lets talk about this at the next TAG meeting and find some volunteers for this project! Maybe you can reach out to Al-Hussein in the meantime to look into the script.

**Comment by guidemetothemoon** [comment]
Cool, thanks for the feedback! I'm all for automating as much as possible, and I would definitely love to know about automating the scraping and auto-generation process, if someone has actually done something similar already. Looking forwards to hearing from your contact person @catblade! I can reach out to Al-Hussein in the meantime and see if he can share his script with us. I can also add this as topic for discussion for the next TAG's meeting @leonardpahlke.

**Comment by leonardpahlke** [comment]
Thanks! :)

**Comment by leonardpahlke** [comment]
Thanks Niki

**Comment by Al-HusseinHameedJasim** [comment]
Regarding the script I've posted about in the tag-environmental-sustainability Slack channel, I've made some improvements to the script and implemented a workflow to automate the scraping process. It now considers additional criteria to capture the most pertinent information.
The script is available in this [repository](https://github.com/Al-HusseinHameedJasim/green-talks-scraper), and the list of talks is published to [talks.md](https://github.com/Al-HusseinHameedJasim/green-talks-scraper/blob/main/talks.md).

**Comment by guidemetothemoon** [comment]
After KubeCon+CloudNativeCon Europe we'll pick up work on finalizing automatic workflow for scraping and automatically generating a green talk session list for different conferences and events that will also be continuously updated on the TAG ENV website.
All further updates for this project will be done in following tracking issue: #345 , therefore closing this issue.
