### ISSUE TITLE
[Proposal] Create an Inclusive Blog/ Getting Starting Guide for Nontechnical Contributors

### ISSUE THREAD

**Issue by berryq460** [cncf/tag-env-sustainability#61]
#### Description
Although this is a predominately technical group, I proposed we create a Getting Starting Guide for nontechnical contributors to participate and lower the barrier to entry, thus boosting the accessibility of our group.

#### Impact

Getting starting guides for non-technical contributors are important for several reasons:

1. Accessibility: Open-source projects can be complex and technical, making it difficult for non-technical contributors to get involved. Getting started guides provide a clear and concise introduction to the project, making it easier for non-technical contributors to get involved.

2. Encouragement: Getting started guides help non-technical contributors feel confident and motivated to contribute to the project, even if they don't have technical skills.

3. Inclusivity: Open-source projects benefit from a diverse range of perspectives and contributions. By providing a getting-started guide for non-technical contributors, projects can encourage and support a wider range of individuals to get involved.

4. Standardization: Getting started guides can help standardize the process for getting involved in a project, making it easier for non-technical contributors to understand what is expected of them.

5. Increased contributions: By providing a clear and accessible way for non-technical contributors to get involved, projects can increase the number and diversity of contributions they receive, leading to better outcomes for the project and its goals.

Overall, getting started guides play an important role in promoting accessibility, inclusivity, and increased contributions to open-source projects.

#### Scope

I propose we should tackle this in 3 steps. Here is the [first draft](https://docs.google.com/document/d/117Mt6sDInSxdsVA-vBI9Cwls67FvQbU2KR1WqqKY0U8/edit?usp=sharing) since I proposed it in the 2/1 meeting. Cara can make edits to the document and formalize it. After this the final review can occur in a meeting.

**Comment by leonardpahlke** [comment]
@berryq460 thanks for opening the issue! As I also said in the meeting, I think this is something that we should definitely work on and improve the current contribution guide. Thanks for kicking this off.

@berryq460 do you mind sharing your [first draft document](https://docs.google.com/document/d/117Mt6sDInSxdsVA-vBI9Cwls67FvQbU2KR1WqqKY0U8/edit?usp=sharing) publicly (maybe with comment access) so others can have a look 🙌?

@jberkus @CathPag @geekygirldawn do you know if we have something like this in the CNCF somewhere already that we can reference / link to or build on?

**Comment by jberkus** [comment]
Lemme tag the folks working on this for the CNCF:

@qedrakamar @KimMcMahon

**Comment by berryq460** [comment]
Don't recall that coming up in the meeting or notes, but yes access has
been shared already.

**Comment by berryq460** [comment]
Call for help with adding screenshots and translating the doc, totally open to collaborating with CNCF!

**Comment by berryq460** [comment]
Thanks for the suggestions, context and insight into what's going on in the kubernetes community. I am so happy to hear this is already in mind there and I'm happy to help contribute to and collaborate on this intiative across open source communities. Who is the lead of the inclusive intiatives and what meetings are these projects normally discussed in?

**Comment by catblade** [comment]
@berryq460  This may be more effective to discuss with the [Contributor Strategy group](https://contribute.cncf.io/about/) first instead of the Environmental Sustainability group.  If you wish to go across organizations, it may be useful to work with them on guidelines or sets of suggestions for various TAGs to follow.  Have you tried contacting them?  They may also already have content.  @amye  are you aware of anything?

**Comment by geekygirldawn** [comment]
I think this is definitely a better fit for TAG Contributor Strategy, since I don't see an environmental component to this proposal. @amye - do you have the ability to move this issue to the TAG-CS repo?

We are actively working on something similar right now in this PR: https://github.com/cncf/tag-contributor-strategy/pull/339 It's not entirely focused on non-technical contributors, but it has some of what they would need to know. 

We also have a [short page on the website on this topic](https://contribute.cncf.io/maintainers/community/contributor-growth-framework/incentivizing-non-code/), so that might be a good starting point to build on with more details.

I recommend dropping into our next TAG Contributor Strategy - Contributor Growth WG meeting next Thursday (23rd) if you are available. Here's a [gdoc with details about the meeting](https://docs.google.com/document/d/1Kx7tZv5wTXQ7uRKxn5d9d2wLsI3Q3Q51A0i06nLvtdI/edit).

This is a great topic and thanks for getting this started!

**Comment by geekygirldawn** [comment]
Also cc: @Riaankl & @carolynvs for visibility

**Comment by Riaankl** [comment]
@berryq460 this is a great addition to the [start contributing to open source #339](https://github.com/cncf/tag-contributor-strategy/pull/339) PR.
We only touched on the types of work that can be done by non-technical contibutors.
Look like this would be a more step-by-step guide. 
Once it is finilized please remind us to add a referance to the [Start Contributing to Open Source](https://github.com/cncf/tag-contributor-strategy/blob/3c62948469b3b9e3416cb5d940e4195b218d6646/website/content/contributors/getting-started.md) file / web link.

**Comment by catblade** [comment]
Thanks to @geekygirldawn to getting @berryq460 the correct information-I was not sure who to tag for this.  I hope @berryq460  can make those meetings and contribute.

**Comment by berryq460** [comment]
I have updated the docs and am seeking second opinions and input. Thanks!

**Comment by caradelia** [comment]
@amye from can you help with moving this issue for @berryq460 ?

> I think this is definitely a better fit for TAG Contributor Strategy, since I don't see an environmental component to this proposal. @amye - do you have the ability to move this issue to the TAG-CS repo?
> 
> We are actively working on something similar right now in this PR: [cncf/tag-contributor-strategy#339](https://github.com/cncf/tag-contributor-strategy/pull/339) It's not entirely focused on non-technical contributors, but it has some of what they would need to know.

**Comment by berryq460** [comment]
@caradelia Great to hear that you have something set in place already. I am taking a back seat on the Sustainability work due to other priorities but will pop in meetings whenever possible. Please let me know how I Can be of help in the future for product roadmap or design or other related questions. Do I have to move my issue or will someone else do it?

**Comment by berryq460** [comment]
@geekygirldawn Hope you are well!! Happy Easter, if you celebrate. Just as an update I wanted to clarify that I was and will continue to be supportive of your groups work in the CNCF around inclusivity and plan to make the next meeting. Thanks for your suggestions @catblade and crew! Here is the plan as per this suggestion (https://github.com/cncf/tag-env-sustainability/issues/60#issuecomment-1500048652)

**Comment by catblade** [comment]
@geekygirldawn  Do you have a link to that blog, regarding TAG Contributor Strategy blog?  That may help.

**Comment by geekygirldawn** [comment]
@catblade @berryq460 Here's a link to the blog post that we did to promote TAG Contributor Strategy: https://www.cncf.io/blog/2022/03/10/the-maintainers-toolkit-must-know-resources-for-cncf-projects/

**Comment by berryq460** [comment]
Thanks @geekygirldawn for your support, clarification and resources. Hope you had fun in AMS! See you in Vancouver!?

**Comment by mkorbi** [comment]
Hey all, during our TAG project meeting at KubeCon EU we discussed shortly on this point. We start driving in the direction of the following:
- We should add to our contributor readme additional resources as the mentioned blog from above, or the kubernetes dev page etc. Overall there are multiple places where this is addressed.
- In addition, we can write a blog about the non technical side (docs, orga, "project management", meetups, events etc.) of contribution (if it doesn't exist yet)

P.S.: we didn't read through all comments here due to lack of time -> discuss in the next meeting?

**Comment by berryq460** [comment]
Linking my update on the blog: https://github.com/cncf/tag-env-sustainability/issues/60#issuecomment-1516865694
I may not be able to make next meet due to schedule conflict, but will see what I can do. Do you ore any other leads have availability to chat 1-1?

**Comment by berryq460** [comment]
As mentioned yesterday at the meeting, we have a shortage of content on our site.  We have no about section on our website and welcoming content for new users. As of now our website is sparse with content and turning down relevant content at this stage may not help bolster our presence in the upstream community.  I already went through  "proper protocols" for raising an issue, creating a first draft and accepting group suggestions. I even verified it with another CNCF body ensuring more than enough buy in on my document. I would like to see this published before VC event meet up to ensure the Qr code leads to something meaningful. I'll feel much more comfortable leading the VC meeting knowing this is taken care of first. Thanks!

**Comment by leonardpahlke** [comment]
Hey @berryq460 could you open up a PR to add your blog post to the TAG ENV website? Thanks!

Not sure if you have done this before? Let me summarize the steps briefly:

1. [Fork the repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo) 
2. [Clone to repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository)
3. create a new markdown file to the folder https://github.com/cncf/tag-env-sustainability/tree/main/website/content/blog 
4. add your blog post to the markdown file 

To add your graphics, we need to upload those png's to a folder.
Since this is the first blog post, could you create a folder under [`/static`](https://github.com/cncf/tag-env-sustainability/tree/main/website/static) with the name `blogs/` and another folder with the date and the blog post name `2023-05-07-<BLOG POST NAME>/` with that your diagrams can be placed under `/website/static/blogs/2023-05-07-<BLOG POST NAME>/***`.

You can add your images to the markdown file by using this `<p class="mt-5 mb-5"><img src="/blogs/2023-05-07-<BLOG POST NAME>/<IMAGE NAME>.png" alt="<ALT DESCRIPTION>"></p>` 

5. After your blog post is replicated, you can commit your changes and open a PR.

Let me know if you get stuck somewhere. You may not look forward to going through this git workflow, but I can tell you that once you've successfully gone through this process, it can take you a long way contributing to any open source project! 🙌

**Comment by berryq460** [comment]
Okay not my first time but a good refresher. I appreciate the walk through
and response😊🙌🏽🙏🏼 Others will benefit as well.

**Comment by berryq460** [comment]
Done: I will be at the conference all day please Edit directly on my behalf adding the images in the following sections. Thanks so much! : https://docs.google.com/document/d/117Mt6sDInSxdsVA-vBI9Cwls67FvQbU2KR1WqqKY0U8/edit?usp=sharing https://github.com/berryq460/tag-env-sustainability/pull/3 @leonardpahlke
