### ISSUE TITLE
[Action] TAG Office Hours Meeting

### ISSUE THREAD

**Issue by leonardpahlke** [cncf/tag-env-sustainability#89]
**This idea came up during Kubecon, and I just followed up on it by putting it up for discussion.**

Idea: Schedule a weekly meeting of about 1 hour duration where we can sit together and work on all things TAG related. 
This should be informal, not necessarily without an agenda.

After we get enough input on this we will discuss this idea in a TAG meeting.

**Comment by leonardpahlke** [comment]
@nikimanoledaki I think you brought this topic up at some point during Kubecon. Would you like to follow this up?

**Comment by nikimanoledaki** [comment]
Hey! I remember discussing this with you in a group but can't remember who else was there, perhaps @by-d-sign or @guidemetothemoon? We could definitely talk through this idea!

Once a WG Comms is created, I imagine that the TAG meeting may open up discussion time to turn into this kind of Office Hours meeting soon  🤔 In the GitOps WG, for example, there tend to be a few minutes in the end of the meeting for impromptu open-ended questions that may be really technical, conceptual, random, etc.

Another issue that we should discuss is that a weekly open meeting would add a lot of overhead for maintainers. There may be an opportunity cost over a different initiative such as for example, twice monthly WG meetings for a more specific topic such as WG Metrics or WG Tools. With this format, we would benefit from the structure and governance of WGs that are already well-established in the CNCF ecosystem.

**Comment by guidemetothemoon** [comment]
I vaguely remember us talking about it during KubeCon+CloudNativeCon..I don't have much experience with the process in other TAGs but I think that @nikimanoledaki has some reasonable reflections here. Having such meeting on a weekly basis can make it a bit challenging to allocate hosts/maintainers due to capacity, availability and limited resources (at least yet, while the TAG is still young and doesn't have a lot of active members who would like to take this kind of lead). 

Another thought I have is that it's hard to say at this point how popular it's going to be and we would probably want to avoid booking meetings and people and not have that many joining or not having much to discuss. Therefore it could be a good idea to start with allocating some time in the end of the regular TAG meeting first and see how much activity it will be there? If there will be a lot to discuss then it would be clear that additional meetings/time are needed.

Having some meetings with a more focused scope as Niki mentions can be a good idea. I think that it can also attract more community members who want to contribute only to a specific area inside of the TAG and scoped meetings with clear expectations for the meeting content can make it easier for them to prioritize and attend such meetings.

Anyway, I'd love to discuss this topic further! 😊

**Comment by AntonioDiTuri** [comment]
I would also be interested in this one! :)
